### PR TITLE
Fix for compatibility with Axios 0.13

### PR DESCRIPTION
**Pull request by braska**

### CODE REVIEW

**Comment by braska** [comment]
More info here: https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#012x---0130

**Comment by braska** [comment]
Don't worry about too many fixes in readme file. Thats work of "Markdown tidy" plugin from my text editor.

**Comment by svrcekmichal** [comment]
@braska Hi, thanks for your PR, looks awesome. I am currently really busy and I will look at all about axios 0.13 later this week. Hope it's ok.

**Comment by themillhousegroup** [comment]
+1 Looking forward to this getting merged :-)

**Comment by svrcekmichal** [comment]
@braska if you have time, please update peer dep of axios to `>= 0.13`. I will the merge it. I will also remove old getState support from interceptors, update readme and change log and publish it as version 2 of middleware because of this breaking changes

**Comment by svrcekmichal** [comment]
@braska @themillhousegroup I've just published 2.0.0 version of this middleware, with support of axios@0.13 ... please, try it, and in case of some bugs, just report it or send PR.

I have also published version 1.3.1 of middleware which changes peer dep of axios to 0.5 - 0.12 to protectet users of version 1

**Pull request merged**
