### PR TITLE
adding basic typings support so the package can be imported and used i…n typescript environment, I didn't make all types available just the basic.

### PR DESCRIPTION
**Pull request by vasilevich**
Added a starting point for typescript typings
so that you can do:
```
import axiosMiddlewareCreator from 'redux-axios-middleware';
export const axiosMiddleware = axiosMiddlewareCreator(axios);
```
please note:
this does not include ALL the types of axiosMiddleware, I hope somebody can take the time and make the rest of the types, because I am not sure how to do it.

Thank you and best of luck!

### CODE REVIEW

**Comment by andrewjrhill** [comment]
Can we get an update on this PR please?

**Comment by kg-currenxie** [comment]
Yes plz!

**Comment by vasilevich** [comment]
these typings served me well, unfortunately, the maintainer of this repo (and the NPM module) is no longer active.  but if you want you can use my fork in your NPM project simpley by writing:
`yarn add https://github.com/vasilevich/redux-axios-middleware.git#53373f5d0027bc914c1ceb85cc173b3137d24e13`

this should work almost exactly like NPM with a specific version (in this case 53373f5d0027bc914c1ceb85cc173b3137d24e13 is the commit)

if you think it is reasonable and not disrespectful to the creator of this repo, I could simpley make a new NPM under a new name with the added features,  otherwise this github will have to do.

Cheers.

**Comment by svrcekmichal** [comment]
sorry guys for late response, the only way I can help you is to make you collaborator of the repo? would that work for you? if not, you can freely fork this as you already did

**Comment by vasilevich** [comment]
yes, please add me as a collaborator, and if you can, also add me as a collaborator on the NPM package so that I can push the changes to NPM repository.
my account on npm.org is same as here:  vasilevich

https://www.npmjs.com/~vasilevich

Thanks for your short notice answer.

**Comment by svrcekmichal** [comment]
@vasilevich you should be added, thanks for taking your time to work on this repository. I really appreciate that even if I no longer have time to do that.

**Comment by vasilevich** [comment]
I merged & published the changes to NPM should have the typings now.

Thanks for your cooperation @svrcekmichal

**Comment by knightus** [comment]
@vasilevich can you also create the version tag on github accordingly. I've seen 4.0.1 in npm but not in github so it's hard to acknoledge the changes until I see the commit history

**Pull request merged**
